"""adding note in integer

Revision ID: 8bebce51c9a8
Revises: f59dc9a46ba2
Create Date: 2026-04-06 11:32:42.672694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bebce51c9a8'
down_revision: Union[str, Sequence[str], None] = 'f59dc9a46ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clothes', 'size',
               existing_type=postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', 'XXXXL', name='sizeenum'),
               nullable=True)
    op.alter_column('clothes', 'status',
               existing_type=postgresql.ENUM('clean', 'dirty', name='statusenum'),
               nullable=True)
    op.alter_column('clothes', 'style',
               existing_type=postgresql.ENUM('boheme', 'vintage', 'classique', 'casual', 'streetwear', 'chic', name='styleenum'),
               nullable=True)
    op.alter_column('clothes', 'season',
               existing_type=postgresql.ENUM('spring', 'summer', 'autumn', 'winter', name='seasonenum'),
               nullable=True)
    op.alter_column('clothes', 'materials',
               existing_type=postgresql.ENUM('cotton', 'linen', 'leather', 'wool', 'viscose', 'spandex', 'polyester', 'lyocell', 'silk', 'cashmere', 'acrylic', 'polyamide', name='materialsenum'),
               nullable=True)
    op.alter_column('clothes', 'note',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clothes', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clothes', 'picture',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'clothes', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clothes', type_='unique')
    op.alter_column('clothes', 'picture',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clothes', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clothes', 'note',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clothes', 'materials',
               existing_type=postgresql.ENUM('cotton', 'linen', 'leather', 'wool', 'viscose', 'spandex', 'polyester', 'lyocell', 'silk', 'cashmere', 'acrylic', 'polyamide', name='materialsenum'),
               nullable=False)
    op.alter_column('clothes', 'season',
               existing_type=postgresql.ENUM('spring', 'summer', 'autumn', 'winter', name='seasonenum'),
               nullable=False)
    op.alter_column('clothes', 'style',
               existing_type=postgresql.ENUM('boheme', 'vintage', 'classique', 'casual', 'streetwear', 'chic', name='styleenum'),
               nullable=False)
    op.alter_column('clothes', 'status',
               existing_type=postgresql.ENUM('clean', 'dirty', name='statusenum'),
               nullable=False)
    op.alter_column('clothes', 'size',
               existing_type=postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', 'XXXXL', name='sizeenum'),
               nullable=False)
    # ### end Alembic commands ###
