"""change name field to be mandatory and add category column in Brands table

Revision ID: ebb637ee0b6c
Revises: f0575bcd67ca
Create Date: 2026-02-20 12:58:34.997319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebb637ee0b6c'
down_revision: Union[str, Sequence[str], None] = 'f0575bcd67ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'category')
    # ### end Alembic commands ###
