"""create all tables

Revision ID: f59dc9a46ba2
Revises: f0575bcd67ca
Create Date: 2026-03-06 13:42:44.781779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f59dc9a46ba2'
down_revision: Union[str, Sequence[str], None] = 'f0575bcd67ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('pseudo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('clothes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('category', sa.Enum('tops', 'shirts', 'blouses', 'trousers', 'skirts', 'shorts', 'dress', 'jacket', 'coat', 'trench', 'sweater', 'cardigan', 'body', 'tshirt', 'blazer', 'vest', 'headwear', 'shoes', 'bags', 'underwear', 'accessories', 'swimwear', name='categoryenum'), nullable=False),
                    sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', 'XXXXL', name='sizeenum'), nullable=False),
                    sa.Column('status', sa.Enum('clean', 'dirty', name='statusenum'), nullable=False),
                    sa.Column('style', sa.Enum('boheme', 'vintage', 'classique', 'casual', 'streetwear', 'chic', name='styleenum'), nullable=False),
                    sa.Column('brand_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('season', sa.Enum('spring', 'summer', 'autumn', 'winter', name='seasonenum'), nullable=False),
                    sa.Column('note', sa.Integer(), nullable=False),
                    sa.Column('materials', sa.Enum('cotton', 'linen', 'leather', 'wool', 'viscose', 'spandex', 'polyester', 'lyocell', 'silk', 'cashmere', 'acrylic', 'polyamide', name='materialsenum'), nullable=False),
                    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('color', sa.Enum('black', 'white', 'grey', 'beige', 'pink', 'purple', 'blue', 'green', 'orange', 'red', 'yellow', 'brown', name='colorenum'), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('by_default', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tags_clothes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    sa.Column('clothe_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['clothe_id'], ['clothes.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('clothe_id', 'tag_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_clothes')
    op.drop_table('tags')
    op.drop_table('clothes')
    op.drop_table('users')
    op.drop_table('brands')
    # ### end Alembic commands ###
